INSERT INTO employees (name, surname, position, military_status, notice_period, phone_number, email, cv)
VALUES ('John', 'Doe', 'Software Engineer', 'EXEMPT', '2 weeks', '123-456-7890', 'john.doe@example.com',
        'dummy_cv_data_1'),
       ('Jane', 'Smith', 'Project Manager', 'COMPLETED', '1 month', '234-567-8901', 'jane.smith@example.com',
        'dummy_cv_data_2'),
       ('Alice', 'Johnson', 'QA Engineer', 'EXEMPT', '3 weeks', '345-678-9012', 'alice.johnson@example.com',
        'dummy_cv_data_3'),
       ('Bob', 'Brown', 'DevOps Engineer', 'COMPLETED', '2 months', '456-789-0123', 'bob.brown@example.com',
        'dummy_cv_data_4'),
       ('Charlie', 'Davis', 'Product Owner', 'EXEMPT', '1 month', '567-890-1234', 'charlie.davis@example.com',
        'dummy_cv_data_5'),
       ('David', 'Wilson', 'Business Analyst', 'EXEMPT', '2 weeks', '678-901-2345', 'david.wilson@example.com',
        'dummy_cv_data_6'),
       ('Eve', 'Martinez', 'HR Manager', 'COMPLETED', '1 month', '789-012-3456', 'eve.martinez@example.com',
        'dummy_cv_data_7'),
       ('Frank', 'Garcia', 'UX Designer', 'EXEMPT', '3 weeks', '890-123-4567', 'frank.garcia@example.com',
        'dummy_cv_data_8'),
       ('Grace', 'Lee', 'Data Scientist', 'COMPLETED', '2 months', '901-234-5678', 'grace.lee@example.com',
        'dummy_cv_data_9'),
       ('Hank', 'Kim', 'System Administrator', 'EXEMPT', '1 month', '012-345-6789', 'hank.kim@example.com',
        'dummy_cv_data_10');